logging:
  level:
    root: info

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.highlight_sql: true
      hibernate.show_sql: true
    open-in-view: false
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
