logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:h2:mem:musinsa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.highlight_sql: true
      hibernate.show_sql: true
    open-in-view: false
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  h2:
    console:
      enabled: true