logging:
  level:
    root: info

spring:
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      data-locations: classpath:init.sql
      schema-locations: classpath:schema.sql
      mode: never
